### ISSUE TITLE
cne_imsa_ind_handler_wl_ wakelock

### ISSUE THREAD

**Issue by T0jgli** [xiaomi-pyxis/android_build_bug-tracker#1]
**ROM Version :*Crdroid Mar 31.* 
**Kernel version:*stock* 
**Android version:*10* 

**Description**
Betterbatterystats shows a cne_imsa_ind_handler_wl_  kernel wakelock.

![Screenshot_20200401-174655](https://i.imgur.com/bPVu5WWh.jpg)

**Symptoms**
Battery drain.

**How to reproduce**
I don't know if that's it's only on my device, but I think it drains my battery.

**Comment by coderzstas** [comment]
I look into it , btw we have boeffla wakelock blocker support in kernel , you can block it yourself

**Comment by T0jgli** [comment]
Nice, I have found this c440000 in fk manager:

![Screenshot_20200401-1746555](https://i.imgur.com/dsAtHI9h.jpg)
